### ISSUE TITLE
Umbraco 12.2 breaks publishing with Deploy

### ISSUE THREAD

**Issue by robertjf** [umbraco/Umbraco.Commerce.Deploy#1]
Refer to issue https://github.com/umbraco/Umbraco.Commerce.Deploy/issues/3 (logged on Umbraco.Commerce.Issues) for details - it looks like the `UmbracoCommerceStoreEntityPickerValueConnector.GetPropertyEntityType` method expects a `Dictionary` instead of a `StoreEntityPickerConfiguration` object.

PR incoming to address this issue, but I'm not 100% sure about backwards compatibility to Umbraco.Commerce v12.0

**Comment by mattbrailsford** [comment]
I've transferred the other issue to this repository so will close this issue to keep the convo together
