### ISSUE TITLE
ValidationException thrown when deploying to a fresh database

### ISSUE THREAD

**Issue by BenWhite27** [umbraco/Umbraco.Commerce.Deploy#10]
v13.1.1

When I clone down the Umbraco Cloud project to my development PC which has no database I'm presented with an error when Umbraco first starts deployment.

```
The source environment has thrown a Umbraco.Deploy.Core.Exceptions.ProcessArtifactException with message: 
Process pass #4 failed for artifact umb://umbraco-commerce-shipping-method/1861c50c2e5f446eb575018fedebed48. 
It might have been caused by an inner Umbraco.Commerce.Common.Validation.ValidationException with message: 
You can't add a Price for a Region the Shipping Method is not allowed in.
```

I've confirmed that the UDA file only contains prices for regions that it's permitted in, so this doesn't seem like a data issue.

I've attached my deploy.log and deploy-failed, and the relevant UDA file.
[deploy.log](https://github.com/user-attachments/files/16549317/deploy.log)
[deploy-failed.txt](https://github.com/user-attachments/files/16549322/deploy-failed.txt)
[umbraco-commerce-shipping-method__1861c50c2e5f446eb575018fedebed48.uda.txt](https://github.com/user-attachments/files/16549549/umbraco-commerce-shipping-method__1861c50c2e5f446eb575018fedebed48.uda.txt)

Looking at the code, if I understand it correctly, it looks like prices are added to the shipping method before it's permitted country/region artifacts are added.  Which would explain why a ValidationException is occurring from Umbraco.Commerce code.

**Impact**
This is preventing the creation of any new environment, both on my local PC and in Umbraco Cloud.
After the deploy fails, the UDA files on disk get modified, leaving me with a very incomplete Umbraco Commerce configuration.

**Comment by mattbrailsford** [comment]
Good catch, and it looks like you might be right that we are processing the prices before the allowed countries are assigned so it would probably make sense to move this to afterwards.

I'll take a look and see if I can replicate it to confirm.

**Comment by BenWhite27** [comment]
Hi Matt
~I just tried a fresh deploy this side but with no shipping method UDA files present to see if I could get a successful deploy which also failed.  This time with this message.~

```
The source environment has thrown a Umbraco.Deploy.Core.Exceptions.ProcessArtifactException with message: 
Process pass #4 failed for artifact umb://umbraco-commerce-country/121d1cf7d38245f9a9d0018acb8c918e. 
It might have been caused by an inner System.NullReferenceException with message: 
Object reference not set to an instance of an object.

The following artifacts might be involved:

umb://umbraco-commerce-country/121d1cf7d38245f9a9d0018acb8c918e~
```
~So, there may be more to fix than just the shipping methods.  Happy to supply an entire copy of my deploy uda files if it helps, in the meantime I'll keep diagnosing.~

Ignore that, probably just because the other UDA file mentions the shipping method as a dependency.

**Comment by mattbrailsford** [comment]
Ok, so i've just pushed a 13.1.2--preview.1 build to our night server if you want to try installing that locally and see if that allows you to then restore. If you can confirm it works I can look to get a patch release pushed out.

You can find details on how to use our nightly feeds here https://docs.umbraco.com/umbraco-cms/fundamentals/setup/install/installing-nightly-builds

**Comment by BenWhite27** [comment]
Thanks Matt,
Installed and tested, initial deployment went smooth, no errors to report.

**Comment by mattbrailsford** [comment]
Excellent! I'll get that pushed out right away then 👍

**Comment by BenWhite27** [comment]
Cheers! #H5YR

**Comment by mattbrailsford** [comment]
Ok, that should be available on NuGet shortly once it's cache has updated 👍
