### ISSUE TITLE
appSettings.json configuration path/location

### ISSUE THREAD

**Issue by tormnator** [umbraco/Umbraco.Commerce.Deploy#5]
In Vendr I had the following in appSettings.json:

```json
  "Vendr.Deploy": {
    "PaymentMethods": {
      "IgnoreSettings": [ "mode" ]
    }
  },
```
What is the corresponding setting with Umbraco.Commerce.Deploy? I can't find any references to this in the documentation or with a quick search at the Deploy source code. It's also not mentioned in the Vendr to Umbraco.Commerce migration guide.

**Comment by mattbrailsford** [comment]
It still exists, but yea, it has moved. You'll want to change your config to the following:

```json
"Umbraco" : {
    "Commerce" : {
        "Deploy": {
            "PaymentMethods" : {
                "IgnoreSettings": [ "mode" ]
            }
        }
    }
}
```

Hope this helps

**Comment by tormnator** [comment]
Thanks, Matt!
